#!/usr/bin/env bash
# daily-ci-audit.sh
# Checks recent CI run conclusions and open Dependabot PRs for stack-agents.
# Writes a dated summary to .claude/debug/ci-audit-YYYY-MM-DD.md.
# Always exits 0 — failures are logged, not thrown.

REPO="kevinvwong/stack-agents"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DEBUG_DIR="${REPO_ROOT}/.claude/debug"
DATE=$(date +%Y-%m-%d)
OUT="${DEBUG_DIR}/ci-audit-${DATE}.md"

mkdir -p "${DEBUG_DIR}"

# ------------------------------------------------------------------
# 1. Gather data
# ------------------------------------------------------------------
CI_JSON=$(gh run list \
  --repo "${REPO}" \
  --branch main \
  --limit 5 \
  --json conclusion,name,createdAt,headBranch \
  2>/dev/null) || CI_JSON="[]"

DEP_JSON=$(gh pr list \
  --repo "${REPO}" \
  --label "dependencies" \
  --state open \
  --json number,title,createdAt \
  2>/dev/null) || DEP_JSON="[]"

# ------------------------------------------------------------------
# 2. Analyse CI runs
# ------------------------------------------------------------------
FAILED_COUNT=$(printf '%s' "${CI_JSON}" | \
  python3 -c "
import sys, json
runs = json.load(sys.stdin)
failures = [r for r in runs if r.get('conclusion') not in ('success', 'skipped', 'neutral', None, '')]
print(len(failures))
for f in failures:
    print(f\"  - {f.get('name','?')} ({f.get('conclusion','?')}) at {f.get('createdAt','?')}\")
" 2>/dev/null) || FAILED_COUNT="0"

FAILED_LINES=$(printf '%s' "${FAILED_COUNT}" | tail -n +2)
FAILED_COUNT=$(printf '%s' "${FAILED_COUNT}" | head -1)

# ------------------------------------------------------------------
# 3. Analyse Dependabot PRs
# ------------------------------------------------------------------
DEP_COUNT=$(printf '%s' "${DEP_JSON}" | \
  python3 -c "
import sys, json
prs = json.load(sys.stdin)
print(len(prs))
" 2>/dev/null) || DEP_COUNT="0"

DEP_LINES=$(printf '%s' "${DEP_JSON}" | \
  python3 -c "
import sys, json
prs = json.load(sys.stdin)
for pr in prs:
    print(f\"  - #{pr.get('number','?')} {pr.get('title','?')} (opened {pr.get('createdAt','?')})\")
" 2>/dev/null) || DEP_LINES=""

# ------------------------------------------------------------------
# 4. Build CI status line
# ------------------------------------------------------------------
if [ "${FAILED_COUNT}" = "0" ]; then
  CI_STATUS="✅ CI clean — last 5 runs on main all passed"
else
  CI_STATUS="⚠️ CI FAILURES: ${FAILED_COUNT} of last 5 runs on main failed"
fi

# ------------------------------------------------------------------
# 5. Write summary
# ------------------------------------------------------------------
{
  echo "# CI Audit — ${DATE}"
  echo ""
  echo "## CI Status"
  echo ""
  echo "${CI_STATUS}"
  if [ -n "${FAILED_LINES}" ]; then
    echo ""
    echo "${FAILED_LINES}"
  fi
  echo ""
  echo "## Dependabot PRs (open, labelled 'dependencies')"
  echo ""
  if [ "${DEP_COUNT}" = "0" ]; then
    echo "No open Dependabot PRs."
  else
    echo "${DEP_COUNT} open Dependabot PR(s):"
    echo ""
    echo "${DEP_LINES}"
  fi
  echo ""
  echo "---"
  echo "_Generated by daily-ci-audit.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
} > "${OUT}"

# ------------------------------------------------------------------
# 6. Prune log files older than 7 days
# ------------------------------------------------------------------
find "${DEBUG_DIR}" -maxdepth 1 -name "ci-audit-*.md" -mtime +7 -delete 2>/dev/null || true

echo "CI audit written to: ${OUT}"
exit 0
