#!/usr/bin/env bash
# weekly-pr-health.sh
# Checks open PRs in stack-agents for staleness, missing reviewers, and
# unresolved CHANGES_REQUESTED decisions older than 48 hours.
# Writes a dated summary to .claude/debug/pr-health-YYYY-MM-DD.md.
# Always exits 0 — issues are logged, not thrown.

REPO="kevinvwong/stack-agents"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DEBUG_DIR="${REPO_ROOT}/.claude/debug"
DATE=$(date +%Y-%m-%d)
OUT="${DEBUG_DIR}/pr-health-${DATE}.md"
CUTOFF_7D=$(date -u -d "7 days ago" +%Y-%m-%dT%H:%M:%SZ)
CUTOFF_48H=$(date -u -d "48 hours ago" +%Y-%m-%dT%H:%M:%SZ)

mkdir -p "${DEBUG_DIR}"

# ------------------------------------------------------------------
# 1. Gather open PRs
# ------------------------------------------------------------------
PR_JSON=$(gh pr list \
  --repo "${REPO}" \
  --state open \
  --json number,title,createdAt,reviewRequests,reviewDecision,updatedAt \
  2>/dev/null) || PR_JSON="[]"

# ------------------------------------------------------------------
# 2. Analyse PRs
# ------------------------------------------------------------------
ANALYSIS=$(python3 -c "
import sys, json

pr_json = '''${PR_JSON}'''
cutoff_7d = '${CUTOFF_7D}'
cutoff_48h = '${CUTOFF_48H}'

try:
    prs = json.loads(pr_json)
except Exception:
    prs = []

flagged = []

for pr in prs:
    num    = pr.get('number', '?')
    title  = pr.get('title', '?')
    created = pr.get('createdAt', '')
    updated = pr.get('updatedAt', '')
    decision = pr.get('reviewDecision', '') or ''
    reviewers = pr.get('reviewRequests', []) or []
    reviewer_count = len(reviewers)

    flags = []

    # Flag: open > 7 days
    if created and created < cutoff_7d:
        flags.append(f'open since {created[:10]} (> 7 days)')

    # Flag: no reviewer assigned
    if reviewer_count == 0:
        flags.append('no reviewer assigned')

    # Flag: CHANGES_REQUESTED and last updated > 48h ago
    if decision == 'CHANGES_REQUESTED' and updated and updated < cutoff_48h:
        flags.append(f'CHANGES_REQUESTED, last updated {updated[:10]} (> 48h ago)')

    if flags:
        flagged.append({'num': num, 'title': title, 'flags': flags})

print(json.dumps(flagged))
" 2>/dev/null) || ANALYSIS="[]"

FLAGGED_COUNT=$(python3 -c "
import sys, json
try:
    items = json.loads('''${ANALYSIS}''')
    print(len(items))
except Exception:
    print(0)
" 2>/dev/null) || FLAGGED_COUNT="0"

# ------------------------------------------------------------------
# 3. Render flagged PR lines
# ------------------------------------------------------------------
FLAGGED_LINES=$(python3 -c "
import sys, json
try:
    items = json.loads('''${ANALYSIS}''')
    for item in items:
        flag_str = '; '.join(item.get('flags', []))
        print(f\"  - PR #{item.get('num','?')}: {item.get('title','?')}\")
        print(f\"    Flags: {flag_str}\")
except Exception:
    pass
" 2>/dev/null) || FLAGGED_LINES=""

# ------------------------------------------------------------------
# 4. Write summary
# ------------------------------------------------------------------
{
  echo "# PR Health — ${DATE}"
  echo ""
  echo "## Open PR Review"
  echo ""
  if [ "${FLAGGED_COUNT}" = "0" ]; then
    echo "✅ All PRs healthy — no staleness, missing reviewers, or unresolved change requests."
  else
    echo "⚠️ ${FLAGGED_COUNT} PR(s) flagged:"
    echo ""
    echo "${FLAGGED_LINES}"
  fi
  echo ""
  echo "### Thresholds"
  echo ""
  echo "| Check | Threshold |"
  echo "|-------|-----------|"
  echo "| Open too long | > 7 days |"
  echo "| No reviewer | any open PR |"
  echo "| CHANGES_REQUESTED stale | last updated > 48h ago |"
  echo ""
  echo "---"
  echo "_Generated by weekly-pr-health.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
} > "${OUT}"

# ------------------------------------------------------------------
# 5. Prune log files older than 7 days
# ------------------------------------------------------------------
find "${DEBUG_DIR}" -maxdepth 1 -name "pr-health-*.md" -mtime +7 -delete 2>/dev/null || true

echo "PR health check written to: ${OUT}"
exit 0
